spring:
  application:
    name: adhd
  profiles:
    active: local   # TODO: 배포 전 반드시 이 줄 삭제!

  # 1. MySQL 연결 설정 (AWS EC2)
  datasource:
    url: jdbc:mysql://100.27.204.252:3306/capstone?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    url: jdbc:mysql://localhost:3306/adhd_local?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 2. JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    # defer-datasource-initialization: true

  # 3. 초기 데이터 설정 (data.sql 실행 옵션)
  sql:
    init:
    # mode: always

#  # 4. ⭐️ OAuth2 클라이언트(구글, 카카오) 접속 설정 (신규 추가) ⭐️
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            scope:
#              - email
#              - profile
#          kakao:
#            client-id: ${KAKAO_CLIENT_ID}
#            client-secret: ${KAKAO_CLIENT_SECRET}
#            client-authentication-method: client_secret_post
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
#            client-name: Kakao
#        # 카카오는 스프링 기본 내장이 아니라서 통신할 주소를 직접 명시
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id


# 5. Swagger API 문서 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha

# 6. JWT 암호화 및 토큰 만료 설정
jwt:
  secret: ${JWT_SECRET}
  access-expiration: 43200000    # 12시간 (1000ms * 60 * 60 * 12)
  refresh-expiration: 1209600000 # 14일 (1000ms * 60 * 60 * 24 * 14)

openai: ${OPENAI_API_KEY}

# Firebase 서비스 계정 키 파일 경로
firebase:
  service-account-path: classpath:firebase-service-account.json

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

